public class crtpao {
    public static void main(String[] args){
        for(int i=0;i<10;i++) {
            for (int x = 0; x < 10; x++) {
                System.out.println("table[" + i + "][" + x + "][1] =\"\"; table[" + i + "][" + x + "][2] =\"\"; table[" + i + "][" + x + "][3] =\"\";");
            }
        }
            String[][][] table = new String[10][10][3];
            table[0][0][1] ="Zlatan Ibrahimović";        table[0][0][2] ="Doing";            table[0][0][3] ="Taekwondo";
            table[0][1][1] ="Lionel Messi";              table[0][1][2] ="Holding";          table[0][1][3] ="Shirt";
            table[0][2][1] ="Neymar Jr.";                table[0][2][2] ="Dancing";          table[0][2][3] ="Samba";
            table[0][3][1] ="Marco Reus";                table[0][3][2] ="Playing";          table[0][3][3] ="Fifa";
            table[0][4][1] ="Robin van Persie";          table[0][4][2] ="FlyHeading";       table[0][4][3] ="Ball";
            table[0][5][1] ="Fernando Torres";           table[0][5][2] ="Swallowing";       table[0][5][3] ="Tongue";
            table[0][6][1] ="Peter Crouch";              table[0][6][2] ="Headbutting";      table[0][6][3] ="The post";
            table[0][7][1] ="Cristiano Ronaldo";         table[0][7][2] ="Celebrating";      table[0][7][3] ="Goal";
            table[0][8][1] ="David Beckham";             table[0][8][2] ="Filming";          table[0][8][3] ="Movie";
            table[0][9][1] ="James Rodríguez";           table[0][9][2] ="Fingering";        table[0][9][3] ="Head";
            table[1][0][1] ="Superman";                  table[1][0][2] ="Eyelazering";      table[1][0][3] ="Ground";
            table[1][1][1] ="Lex Luthor";                table[1][1][2] ="Planting";         table[1][1][3] ="Zeus Hair";
            table[1][2][1] ="Nightwing";                 table[1][2][2] ="Feeding";          table[1][2][3] ="Batman's Fish";
            table[1][3][1] ="Martian Manhunter";         table[1][3][2] ="Reading";          table[1][3][3] ="Minds";
            table[1][4][1] ="Raven";                     table[1][4][2] ="Opening";          table[1][4][3] ="Dimensional Port";
            table[1][5][1] ="Flash";                     table[1][5][2] ="Bumping";          table[1][5][3] ="Wall";
            table[1][6][1] ="Batman";                    table[1][6][2] ="Releasing";        table[1][6][3] ="Bats";
            table[1][7][1] ="Catwoman";                  table[1][7][2] ="Stealing";         table[1][7][3] ="Diamonds";
            table[1][8][1] ="Harley Quinn";              table[1][8][2] ="Hitting";          table[1][8][3] ="Baseball Bat";
            table[1][9][1] ="Joker";                     table[1][9][2] ="Firing";           table[1][9][3] ="Bazooka";
            table[2][0][1] ="Spiderman";                 table[2][0][2] ="Webbing";          table[2][0][3] ="Thief's Crotch";
            table[2][1][1] ="Loki";                      table[2][1][2] ="Faking";           table[2][1][3] ="Death";
            table[2][2][1] ="Nick Fury";                 table[2][2][2] ="Adjusting";        table[2][2][3] ="Eye Patch";
            table[2][3][1] ="Mystique";                  table[2][3][2] ="Poisoning";        table[2][3][3] ="Cyrebro";
            table[2][4][1] ="Rogue";                     table[2][4][2] ="Putting Down";     table[2][4][3] ="Fire";
            table[2][5][1] ="Falcon";                    table[2][5][2] ="Launching";        table[2][5][3] ="Missiles";
            table[2][6][1] ="Black Widow";               table[2][6][2] ="Blocking";         table[2][6][3] ="Grenade";
            table[2][7][1] ="Captain America";           table[2][7][2] ="Frisbeeing";       table[2][7][3] ="Sheild";
            table[2][8][1] ="Deadpool";                  table[2][8][2] ="Cutting";          table[2][8][3] ="Kebab";
            table[2][9][1] ="Gambit";                    table[2][9][2] ="Throwing";         table[2][9][3] ="Cards";
            table[3][0][1] ="Selena Gomez";              table[3][0][2] ="Killing With";     table[3][0][3] ="Kindness";
            table[3][1][1] ="Lana Del Rey";              table[3][1][2] ="Shooting Down";    table[3][1][3] ="Helecopter";
            table[3][2][1] ="Nicki Minaj";               table[3][2][2] ="Getting";          table[3][2][3] ="Tan";
            table[3][3][1] ="Miley Cyrus";               table[3][3][2] ="Humping";          table[3][3][3] ="Wall";
            table[3][4][1] ="Rihanna";                   table[3][4][2] ="Slapping";         table[3][4][3] ="Michael Cera";
            table[3][5][1] ="Fergie";                    table[3][5][2] ="Shaking";          table[3][5][3] ="MILF";
            table[3][6][1] ="Bebe Rexha";                table[3][6][2] ="Dancing With";     table[3][6][3] ="Somebody";
            table[3][7][1] ="Ke$ha";                     table[3][7][2] ="Boobing";          table[3][7][3] ="Piano";
            table[3][8][1] ="Demi Lovato";               table[3][8][2] ="Shining";          table[3][8][3] ="Neon Lights";
            table[3][9][1] ="Jennifer Lopez";            table[3][9][2] ="Twerking";         table[3][9][3] ="Booty";
            table[4][0][1] ="Xenia Tchoumitcheva";       table[4][0][2] ="Wearing";          table[4][0][3] ="White Socks";
            table[4][1][1] ="Lily Aldridge";             table[4][1][2] ="Training Like";    table[4][1][3] ="Angel";
            table[4][2][1] ="Nathalie Cox";              table[4][2][2] ="Finishing";        table[4][2][3] ="Exam";
            table[4][3][1] ="Martha Hunt";               table[4][3][2] ="Tweeting";         table[4][3][3] ="Questions";
            table[4][4][1] ="Rosie Huntington-Whiteley"; table[4][4][2] ="Walking With";     table[4][4][3] ="Naked Butt";
            table[4][5][1] ="Florence Brudenell-Bruce";  table[4][5][2] ="Smelling";         table[4][5][3] ="Flower";
            table[4][6][1] ="Bella Hadid";               table[4][6][2] ="Priding";          table[4][6][3] ="Islam";
            table[4][7][1] ="Karlie Kloss";              table[4][7][2] ="Eating";           table[4][7][3] ="Sandwich";
            table[4][8][1] ="Dytto";                     table[4][8][2] ="Tutting";          table[4][8][3] ="Fingers";
            table[4][9][1] ="Josie Maran";               table[4][9][2] ="Misleading";       table[4][9][3] ="Cops";
            table[5][0][1] ="Stephanie Mcmahon";         table[5][0][2] ="Having";           table[5][0][3] ="Bella Appetite";
            table[5][1][1] ="Lita";                      table[5][1][2] ="Sleeping In";      table[5][1][3] ="Ring";
            table[5][2][1] ="Nikki Bella";               table[5][2][2] ="Staying";          table[5][2][3] ="Fearless";
            table[5][3][1] ="Miz";                       table[5][3][2] ="Holding";          table[5][3][3] ="Mic";
            table[5][4][1] ="Ronda Rousey";              table[5][4][2] ="Breaking";         table[5][4][3] ="Arms";
            table[5][5][1] ="Vince Mcmahone";            table[5][5][2] ="Summoning";        table[5][5][3] ="Minions";
            table[5][6][1] ="Brie Bella";                table[5][6][2] ="Setting";          table[5][6][3] ="The Mode";
            table[5][7][1] ="Kelly Kelly";               table[5][7][2] ="Pointing At";      table[5][7][3] ="Audience";
            table[5][8][1] ="David Blaine";              table[5][8][2] ="Spitting";         table[5][8][3] ="Fish";
            table[5][9][1] ="Jeff Hardy";                table[5][9][2] ="Whispering In";    table[5][9][3] ="The Wind";
            table[6][0][1] ="Hope Solo";                 table[6][0][2] ="Saving";           table[6][0][3] ="Penalty";
            table[6][1][1] ="Wonder Woman";              table[6][1][2] ="Whipping";         table[6][1][3] ="Whip";
            table[6][2][1] ="Iron Man";                  table[6][2][2] ="Paying";           table[6][2][3] ="Cash";
            table[6][3][1] ="Hilary Duff";               table[6][3][2] ="Turning Into";     table[6][3][3] ="Confetti";
            table[6][4][1] ="Heidi Klum";                table[6][4][2] ="Imitating";        table[6][4][3] ="Jessica Rabbit";
            table[6][5][1] ="AJ LEE";                    table[6][5][2] ="Seducing";         table[6][5][3] ="Wrestlers";
            table[6][6][1] ="Hager Mohammed";            table[6][6][2] ="Shutting";         table[6][6][3] ="Mouth";
            table[6][7][1] ="Eminem";                    table[6][7][2] ="Waving";           table[6][7][3] ="Middle Finger";
            table[6][8][1] ="Angelina Jolie";            table[6][8][2] ="Curving";          table[6][8][3] ="Bullet";
            table[6][9][1] ="Will Smith";                table[6][9][2] ="Killing";          table[6][9][3] ="Dog";
            table[7][0][1] ="Sam Smith";                 table[7][0][2] ="Fucking";          table[7][0][3] ="Boy";
            table[7][1][1] ="Lil Wayne";                 table[7][1][2] ="Signing";          table[7][1][3] ="Tits";
            table[7][2][1] ="Nial Horan";                table[7][2][2] ="Slowing";          table[7][2][3] ="Hands";
            table[7][3][1] ="Michael Jackson";           table[7][3][2] ="Moonwalking With"; table[7][3][3] ="Gloves";
            table[7][4][1] ="R.Kelly";                   table[7][4][2] ="Dangling On";      table[7][4][3] ="Couch";
            table[7][5][1] ="frank sinatra";             table[7][5][2] ="Drinking";         table[7][5][3] ="Whiskey";
            table[7][6][1] ="Pitbull";                   table[7][6][2] ="Pounding";         table[7][6][3] ="Alarm";
            table[7][7][1] ="Kanye West";                table[7][7][2] ="Pirating";         table[7][7][3] ="Software";
            table[7][8][1] ="Twista";                    table[7][8][2] ="Chopping";         table[7][8][3] ="Songs";
            table[7][9][1] ="Justin Bieber";             table[7][9][2] ="Saying";           table[7][9][3] ="Sorry";
            table[8][0][1] ="Scarlett Johanson";         table[8][0][2] ="Tripping On";      table[8][0][3] ="Sidewalk";
            table[8][1][1] ="Lindnsay Lohan";            table[8][1][2] ="Reciting";         table[8][1][3] ="Quran";
            table[8][2][1] ="Nicole Kidman";             table[8][2][2] ="Changing";         table[8][2][3] ="Clothes";
            table[8][3][1] ="Megan Fox";                 table[8][3][2] ="Laying On";        table[8][3][3] ="Motorbike";
            table[8][4][1] ="Rosamund Pike";             table[8][4][2] ="Slitting";         table[8][4][3] ="Throat";
            table[8][5][1] ="Vanessa Hudgens";           table[8][5][2] ="Robbing";          table[8][5][3] ="Restaurant";
            table[8][6][1] ="Blake Lively";              table[8][6][2] ="Kicking";          table[8][6][3] ="Shark";
            table[8][7][1] ="Cara Delevigne";            table[8][7][2] ="Shaving";          table[8][7][3] ="Head";
            table[8][8][1] ="Teresa Palmer";             table[8][8][2] ="Teasing";          table[8][8][3] ="Captive";
            table[8][9][1] ="Charlize Theron";           table[8][9][2] ="Kissing";          table[8][9][3] ="Dead Fish";
            table[9][0][1] ="Sam Jackson";               table[9][0][2] ="Leaning On";       table[9][0][3] ="Seat";
            table[9][1][1] ="Leo Dicaprio";              table[9][1][2] ="Banging/Drawing";  table[9][1][3] ="Margot Robbie/Naked Girl";
            table[9][2][1] ="Nicholas Hoult";            table[9][2][2] ="Transforming to";  table[9][2][3] ="Beast";
            table[9][3][1] ="Mark Wahlberg";             table[9][3][2] ="Working out";      table[9][3][3] ="Belly";
            table[9][4][1] ="Ryan Gosling";              table[9][4][2] ="Laughing at";      table[9][4][3] ="Oscars";
            table[9][5][1] ="Vin Diesel";                table[9][5][2] ="Riding";           table[9][5][3] ="American Muscle";
            table[9][6][1] ="Paul Walker";               table[9][6][2] ="Jumping Off";      table[9][6][3] ="Bus Top";
            table[9][7][1] ="keanu reeves";              table[9][7][2] ="Dodging/Fighting"; table[9][7][3] ="Bullets/Clones";
            table[9][8][1] ="Tom Cruise";                table[9][8][2] ="Sitting on";       table[9][8][3] ="Khalefa Tower";
            table[9][9][1] ="Jared Leto";                table[9][9][2] ="Singing";          table[9][9][3] ="Rock";
    }
}
